### ISSUE TITLE
active? support for multiple paths?

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#103]
Would be helpful to be able to pass multiple tests through to `active?` or have a second method (`active_any?`) available for cases where a site section might have multiple fairly disparate components.

This has come up because family letters has sections like "research" which contain urls along the lines of `/research`, `/research/1` etc, but then the `/search` URL also fits under the research section in terms of the navbar.....at least at this moment in time.

I can foresee this being an issue for whitman and other projects coming up, as well.
The only tricky part of it would be figuring out how to represent the parameter checking part...right now that's an entirely separate argument in the method, but we might need to tie it to a specific entity being passed into the first argument.

If we went with the `active_any?` option, we still have to get through the tricky part above, but it would perhaps be a little easier to say something like:

```
args.each do |arg|
  if active?(arg).present?
    return active?(arg)  # bust out of the loop and return that particular value
end
```

One thing I did play around with a little, at first, was just to chain calls to `active?` together to see if any were true, but because they return an empty string if they are not active, it makes it a little harder to do something concise like 

```
(url :  /research)
<% research_active = active?(search_path) || active?("/research") %>
```

**Comment by techgique** [comment]
Did we have to do something like this for another project in the past with less intuitive nav as well?

I haven't worked with `active?` in a while but I know I had thought about making it able to handle arrays for both the test values and the comparison values. Code that checks if the parameter is an array or not then processes each value. Likely by just wrapping the argument passed in as an array and then looping to decrease if/else logic.

I'll want to review how things currently work before signing off on a strategy though. I can't remember if it handles RegExp's for comparing. If so, I may have used that as a way to test against multiple values with something like `/(?:(re)?search/` for this case or `(?:value1|different-value2)`

**Comment by jduss4** [comment]
@techgique yes, it can handle regex if you pass in a comparison `request.path` or something like that as well.  Otherwise it bombs out because rails doesn't support regex for `current_path?` I think?

I think the regex only solution would work okay unless if you had a situation where it was something like `if URL matches this regex OR the parameter is "x" while URL is "y"`...and then still, we could just write code to check that per project if we really wanted to

**Comment by techgique** [comment]
Yeah, I think if it were something more complex like that, we'd just as well write the logic in the app. Don't really want the `active?` method to spiral out into a really complex mass of code and use cases. Unless if we see a really common pattern across different apps. Then maybe we could centralize it.

**Comment by techgique** [comment]
I'm pretty sure you're correct that `current_path?` doesn't support RegExp :(

**Comment by jduss4** [comment]
I'm fine with keeping the logic specific to each app, then, although if this becomes a fairly common thing then I would be tempted to go for the `active_any?` type solution that just calls `active?` repeatedly but does the checking for blank, etc.  I'll close this for now!
