### ISSUE TITLE
Overlap of pagination with lengthy sort options

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#109]
<img width="980" alt="Screen Shot 2019-04-19 at 10 25 54 AM" src="https://user-images.githubusercontent.com/2480492/56430980-df6ec480-628d-11e9-96f0-6d8f37bf48e4.png">

Clicking on the right side of the sort dropdown doesn't work when the sort is particularly long!

**Comment by techgique** [comment]
D'oh. Looks like CSS or Bootstrap responsive class fix will be necessary

**Comment by techgique** [comment]
This appears to be fixed / I can't recreate it. The text in the sort button appears to wrap now. I'm not sure where that was changed, as this seems to be the last change in the related template: https://github.com/CDRH/orchid/commit/fa1f7660d3ff647e971c4723002daa3e5bf89ecf#diff-7ef0eba12fd73d71973d2b57afe7f88cb882eb6dbd51190df5be1d1f584ea24b

This is what I see now:
![button-text-wraps](https://user-images.githubusercontent.com/8347732/120037827-dd78a300-bfc7-11eb-948b-11c369405ad6.png)

I can sort of force it by using a long string that doesn't wrap, but this probably isn't a likely scenario in real use:
![extra-long-string-no-spaces](https://user-images.githubusercontent.com/8347732/120037926-0ac55100-bfc8-11eb-8e6a-8b34b33c8af0.png)
