### ISSUE TITLE
rows bug

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#114]
When I try to change the number of rows either through a config file or manually through the URL, the pagination UI changes as expected, but the actual number of results being returned does not change!!!

I haven't attempted to track down where this is going wrong, but it could be either in the orchid controller, the api_bridge, or the api itself, potentially.

First discovered while working on nebraskaland and then confirmed behavior on cather letters:

https://cather.unl.edu/letters/search?q=water&text_typex=0&rows=2

the above should return 2 results from 49 possible but instead it displays all the results at once

**Comment by jduss4** [comment]
Looks like pagination might be using `rows` while api is using `num`
https://cather.unl.edu/letters/search?q=water&text_typex=0&num=2

**Comment by techgique** [comment]
Is this getting mixed up between different aspects of site behavior? I guess "rows" is often the term used in MariaDB / MySQL, but outside of that context it might be assumed to mean how many visual rows are displayed on a page which would be confusing to the lay person who might look at the query params and try to experiment.

I think "num" or "results" is a more straightforward param name to users if they want to control how many results are returned for a query :thinking:

**Comment by jduss4** [comment]
I think it might be a solr vs elasticsearch terminology confusion.  I think at this point it might be best to leave the API with num and change the later orchid versions to num, but put something in API Bridge that can support old versions?

**Comment by techgique** [comment]
Okay. Sounds like a reasonable approach to me

**Comment by jduss4** [comment]
api_bridge addresses here: https://github.com/CDRH/api_bridge/releases/tag/v0.0.4
