### ISSUE TITLE
Create better way to include Google Fonts in header

### ISSUE THREAD

**Issue by karindalziel** [CDRH/orchid#116]
Currently I am overwriting the template like this 

https://github.com/CDRH/nebraskaland/blob/2230408fecdc0883efef24848c474e0c011a3864/app/views/layouts/head/_stylesheets.html.erb

But maybe we should have a sub template to make this less disruptive.

**Comment by techgique** [comment]
Jess had started on this in https://github.com/CDRH/orchid/commits/reorg_files and I pushed a couple more commits including moving the default Orchid fonts into the overrideable partial :+1:
