### ISSUE TITLE
Set a single H1 with only page title

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#119]
Based on this: https://webaim.org/projects/screenreadersurvey7/#heading

So I envision this as the h1 on the site root page has the site title, but all others have the item name or "Browse", "Search", "About ___", etc

I think this is probably a wise approach. AT users probably don't need the site title read to them every page on our sites when they are scanning headings in page structure.

I don't anticipate this would cause SEO problems either, but that's the only reason I could see to maybe not do this.

**Comment by wkdewey** [comment]
This is already true of Orchid, isn't it? Looking around at H1's in the code, and at various Orchid sites.

**Comment by techgique** [comment]
Yep, this looks good!
