### ISSUE TITLE
Delete duplicated locale param

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#126]
When `params` is duplicated for creating links to remove facets etc, the `locale` param is present in the URLs. It hasn't been deleted between duplication and passing the modified `params` to path helpers. If there are any other params we routinely delete in these use cases, perhaps we should define a centralized list or method and call that.

**Comment by jduss4** [comment]
Sounds good. I know that in multiple places I have removed things like controller / action / utf8 and some of those rails-background type params, so that's a start to a list anyway!

**Comment by techgique** [comment]
Resolved in https://github.com/CDRH/orchid/commit/5d8b6caed23814b9838aaebf473e74b720e40a48
