### ISSUE TITLE
fixes to documents and configs

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#139]
When spinning up a new app on current dev, the title / subtitle type settings aren't being copied into the new app correctly after user selection.

Also, need to update document for sections:
https://github.com/CDRH/orchid/blob/dev/docs/README.md#section-config

**Comment by jduss4** [comment]
Add note to documentation in https://github.com/CDRH/orchid/blob/dev/docs/README.md#section-links

Can link to different section paths from outside of that section by using the longer version of the pathname:  `<%= link_to "Section", section_home_path %>

**Comment by jduss4** [comment]
would be helpful if the `@section` setting was available in all views / helpers on any pages related to the section, not just on search / browse pages.  For example, just now I was trying to set up text that would display differently based on whether this was the home home page, or the habeas corpus home page, but the @section setting is not available.

**Comment by jduss4** [comment]
In retrospect, I don't see why it isn't already working:  https://github.com/CDRH/orchid/blob/dev/app/controllers/application_controller.rb#L74

**Comment by jduss4** [comment]
We should maybe add `section: section` as defaults to the additional paths, and perhaps that would fix the issue?  https://github.com/CDRH/orchid/blob/dev/config/routes.rb#L16

**Comment by techgique** [comment]
I'm open to making all the other routes section-compatible. The remaining pages should be pretty simple to add that to. I didn't on the other branch as it wasn't necessary for the Cather app

**Comment by jduss4** [comment]
Sounds good, I'll work on it!  Since the other pages don't even have links the way that search / browse does, I think it will be pretty easy to add it to routes for now, and I'll look into adding it by scope!
