### ISSUE TITLE
render_overridable for all orchid actions?

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#150]
recently @karindalziel was trying to override the "about" page for a section
and it wasn't working so she had to add a route to point at it instead of using orchid
I'm thinking that probably we just need a `render_overridable` type thing in each
orchid action in order to provide that behavior

That would potentially be useful for the home page, also, I think?  Am I overlooking any reasons why this hasn't already been done, like problems it would cause?

**Comment by techgique** [comment]
https://github.com/CDRH/orchid/pull/159
