### ISSUE TITLE
Double div class="row" 

### ISSUE THREAD

**Issue by karindalziel** [CDRH/orchid#186]
![Screen Shot 2020-04-29 at 10 56 04 AM](https://user-images.githubusercontent.com/284315/80619403-49c25500-8a0a-11ea-9614-597a203cd698.png)

the default templates in orchid double the `<div class="row">` divs

The problem starts here, there is another div with a class of row int he called template https://github.com/CDRH/orchid/blob/50bf56c4d5d609f451d8ba47c9b57422102fd3b9/app/views/items/index.html.erb#L9 

This puts an extra 20px of padding into the page, increasing the width beyond the border box when the page is smaller than tablet sized.

**Comment by jduss4** [comment]
@karindalziel what would you recommend as a solution?
