### ISSUE TITLE
namespace generator commands

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#187]
when I first created the generator I wasn't thinking ahead as much as I should have. Ideally, the `setup` command would actually be `orchid:setup`.  Since apps only run that command on creation, as long as the documentation was updated I don't think such a change would break backwards compatibility?

**Comment by techgique** [comment]
May even want to work on this alongside #181, which would be a very helpful feature

**Comment by jduss4** [comment]
Definitely.  I predict this one will be a real quick fix, whereas the other will require some development, but if we're in there working on stuff we might as well try!

**Comment by jduss4** [comment]
Okay, for now I'm not going to work on #181 at the same time, because that's a rake task and the generator is not, but I will try to get to an update task soon!
