### ISSUE TITLE
public.yml file and thumbnail size

### ISSUE THREAD

**Issue by karindalziel** [CDRH/orchid#212]
I started a new orchid site from scratch:

`gem 'orchid', git: 'https://github.com/CDRH/orchid', tag: 'v3.1.0'`

and the public.yml file had this for thumbnail size:

`thumbnail_size: !200,200`

However, in orchid's code, that variable is in quotes: 

https://github.com/CDRH/orchid/blob/master/lib/generators/templates/public.yml#L21

On my computer, the code won't run without the quotes, but on my old computer it didn't matter

**Comment by jduss4** [comment]
I figured out what's going on.  The Orchid template starts correctly with `"!200,200"` but then the setup generator asks the user what size they want, and sticks that in without any quotation marks.

**Comment by karindalziel** [comment]
ah! good to know. so either change generator instructions or the way it sticks it in the file
