### ISSUE TITLE
Problem with error checking

### ISSUE THREAD

**Issue by wkdewey** [CDRH/orchid#232]
```
def check_response
    if !@res || (@res.key?("error") && @res.error)
      flash[:error] = t "errors.api"
    end
  end
```
This code fails if @res is an APIBridge object, with `undefined method `key?' for #<ApiBridge::Response:0x00007ffa05480f10>`.

**Comment by techgique** [comment]
Will mentioned Habeas exhibited this problem on the `/search` page.
Habeas code at the time: https://github.com/CDRH/habeascorpus/commit/7733a3465c39f157ca20a35568495212f9f539de

**Comment by wkdewey** [comment]
This is due to how Orchid retrieves the items:
```
def item_retrieve(id)
    byebug
    # @res = @items_api.get_item_by_id(id).first
    @res = @items_api.get_item_by_id(id)
```

**Comment by wkdewey** [comment]
Since other code expects `@res` to be a hash in the case of an individual item, I moved `check_response` out of `show` and changed `item_retrieve` as follows:
```
@res = @items_api.get_item_by_id(id)
    check_response
    @res = @res.first
```
