### ISSUE TITLE
Repeatedly clicking facets will repeat in search blurbs

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#44]
![image](https://user-images.githubusercontent.com/2480492/31553802-39faceda-b001-11e7-9f7d-78bcb01ef25d.png)

I don't know what those are called

**Comment by karindalziel** [comment]
Perhaps we want to make the facets that have been chosen NOT links so they can't be clicked?

**Comment by jduss4** [comment]
@karindalziel that sounds like a very easy solution and I like it :)
I can otherwise also squash down the outgoing array so that duplicates are made one
OR BOTH!
