### ISSUE TITLE
Fix the way index pages are styled

### ISSUE THREAD

**Issue by karindalziel** [CDRH/orchid#55]
The current way index pages work is prone to breaking. 

![screen shot 2017-10-31 at 9 47 44 am](https://user-images.githubusercontent.com/284315/32230231-ae78a156-be20-11e7-84ea-62825d0b9c73.png)

Right now, that section in yellow has to match the background color of the page, or else the dots show all the way across. This leads to breaking in orchid enabled apps, because if you change the background color you then have to overwrite this item or it looks strange (the background stays light blue). 

To fix this, we should either: 

1: change the way this works altogether so it isn't so fussy
2: Set a variable for background color that will change the index item bg's when overwritten. I'm not sure exactly how this would work yet.

**Comment by techgique** [comment]
There ought to be a Sass variable for this, but I don't think I saw one when I looked for it in the bootstrap overrides file.

**Comment by jduss4** [comment]
Relevant to https://github.com/Willa-Cather-Archive/letters-rails/issues/176 ?

**Comment by techgique** [comment]
Addressed in #65
