### ISSUE TITLE
Separate sorting logic for browse page and facets results

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#58]
The Cather Archive wanted the sort flipped to alphabetical by default for the browse pages, but that also toggled the result facets on the search page to alphabetical instead of count.  We may want to hard code those so that they are always by count, since they are search results, or uncouple the setting.

**Comment by karindalziel** [comment]
I think hard coding them would make sense. Unless we change things drastically, I don't think we'd want the search page to ever be alpha.

**Comment by jduss4** [comment]
Decided in slack discussion to create config to accommodate any future requirements for projects.  Will use
`sort` (search documents)
`sort_facet` (search facets)
`sort_browse` (browse facets)

**Comment by jduss4** [comment]
Done in https://github.com/CDRH/orchid/pull/63
