### ISSUE TITLE
Default item's date link broken

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#75]
By default, orchid ships with certain fields displayed as metadata, including "date_display":

<img width="384" alt="image" src="https://user-images.githubusercontent.com/2480492/42824591-bdc24382-89a5-11e8-8d34-844ea78cc544.png">

However, when you click that link, you get an error:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2480492/42824642-d49686a4-89a5-11e8-80d6-ee0cd4203c4a.png">

Without looking into it too much, I assume it's because date_display is not a facet listed in facets.rb.  We should probably adjust either the metadata displaying or the facet file's information.  We also might want to make it so that undescribed facets gracefully fail instead of bringing everything to a dramatic halt.

**Comment by techgique** [comment]
The error `undefined method '[]' for nil:NilClass` and the highlighted line makes it look like `info` isn't defined, so that seems to be the trail of crumbs to follow.

**Comment by jduss4** [comment]
Yeah, info is coming from here:  `<% info = Facets.facet_info[type] %>`
which is why I kinda suspect that since `date_display` isn't in the facets.rb file, it's getting upset that it can't find things like the label, etc.

I just got lucky that I clicked that particular metadata field to go back to the search page and found our charming bug :)

**Comment by jduss4** [comment]
closed with https://github.com/CDRH/orchid/pull/82
