### ISSUE TITLE
site_section method foiled by sub-URIs

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#85]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/2480492/43548439-8290383c-95a3-11e8-94a9-17067eba73b0.png">

There are regex taking apart the `request.path` in the application_helper:  https://github.com/CDRH/orchid/blob/dev/app/helpers/orchid/application_helper.rb#L93

but these are foiled by the sub-URI

**Comment by techgique** [comment]
Looks like we'll have to add code that looks at config or env variables first. I forget where we can check the app's global sub-uri though.

**Comment by jduss4** [comment]
I'm kinda remembering that there's a rails method we can snag to provide the suburi, but I couldn't find it when I was quickly looking for it the day that came up :/

**Comment by techgique** [comment]
Updated link to relevant code: https://github.com/CDRH/orchid/blob/dev/app/helpers/orchid/application_helper.rb#L239

**Comment by techgique** [comment]
I think `config.relative_url_root` may be what we were thinking of before: https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

**Comment by jduss4** [comment]
Agreed, it looks like that worked for African Poetics:  https://github.com/CDRH/african_poetics/blob/master/app/views/layouts/body/_navbar_section.html.erb#L9

**Comment by jduss4** [comment]
I will check with @karindalziel if it's okay that without the suburi, cather letters is currently showing up as "search" rather than as "writings" or "writings-search" or something along those lines for this class.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/2480492/80816325-f29cbb80-8b94-11ea-9e6b-763bb1ddc6c8.png">
