### ISSUE TITLE
Orchid gem via Github

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#9]
On both the server and my workstation, adding the Orchid gem to a new Rails app Gemfile via GitHub seems to fail during app generation with:
```ruby
/usr/local/rvm/gems/ruby-2.4.1@orc/bundler/gems/orchid-6ea5a22ad959/lib/generators/setup_generator.rb:107:in `gems': undefined method `api_bridge_version' for Orchid:Module (NoMethodError)
```

Adding the gem via the `path: '...'` approach works fine on both though.

**Comment by jduss4** [comment]
That's very strange.  When I first created the letters app on cather, I used the github version of orchid to make sure it was working before switching to the local copy.  I thought you had seen that error once before and it's tied to this commit somehow:  https://github.com/CDRH/orchid/commit/8e6065ae538a8938d188d142bec45511fb24f380

**Comment by jduss4** [comment]
Can you post the line you're using in the Gemfile?

**Comment by karindalziel** [comment]
I had this problem too. Gemfile line: 

```
gem 'orchid', git: 'https://github.com/CDRH/orchid'
```

and here's when setup errored out: 

![screen shot 2017-06-22 at 11 05 18 am](https://user-images.githubusercontent.com/284315/27444685-bff6b29c-573c-11e7-910e-ae87387b7405.png)
