### ISSUE TITLE
Make pagination and result markup accessible

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#98]
How do we make our pagination more accessible, especially to screen readers / assistive technologies (SR/AT)? I left the text "Prev" and "Next" on those links to provide minimal text, but I imagine we'll want screen readers to read pagination links as "Previous page", "Next page", "Page #", etc.

If we have markup that SR/AT can read as intended, can/should we some or all of that text from visually-abled users?

[Bootstrap Pagination Documentation](https://getbootstrap.com/docs/3.3/components/#pagination)

If not using Bootstrap, we may want to add `.sr-only`, `.sr-only-focusable`, `.text-hide`, and/or similar classes to hide SR/AT-only and image replacement text.

Also don't forget about using `aria-describedby`, `aria-hidden`, `aria-invalid`, `aria-label`, `aria-labelledby`, `aria-pressed`, etc HTML attributes.

**Comment by karindalziel** [comment]
Deleted my comment from before because I totally misunderstood this the first time I read it.

**Comment by jduss4** [comment]
I think the pagination may have been done here:  https://github.com/CDRH/orchid/commit/6ff42335f0cae32dee9de3bc45c6cc15dbc456d0#diff-2c9daf86e3644705fac5ccf07986406f

I just went to add this to the paginator and was like "hmm, it looks pretty good to me, actually!" and then figured out why haha

**Comment by techgique** [comment]
Ah, I remember doing that. If there's anything further to do there, we'll make another issue in the future.
